services:
    php-server:
        build:
            context: ./backend
            dockerfile: ../Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./backend:/var/www/html
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    default-composer:
        image: composer:2
        container_name: default-composer
        environment:
            COMPOSER_PROCESS_TIMEOUT: 60000
        volumes:
            - ./backend:/app
        working_dir: /app
        command: bash -c "composer install"
